### ISSUE TITLE
politics

### ISSUE THREAD

**Issue by annepetersen** [publicinteresttown/pit-jekyll#3]
the norm on posting CWs about politics probably bears further discussion. As one example:

> Seen several "put content warnings on politics" posts and I don't know how to tell white people that 90% of all life is politics. You're asking people to hide the stuff you find unpalatable and that's not a reasonable thing to expect other people to do for you.

[seldo](https://mastodon.social/@seldo/109377063740135197)

**Comment by krusynth** [comment]
I definitely would like to have more discussion about this! (And I have nothing but infinite respect for Laurie!) Here are my thoughts on the matter, just as a counterpoint. I'm kind of stuck on two ideas. I'm not sure they're _necessarily_ in conflict:

One is what you've got listed above. All things are political! And technology certainly moreso than most topics. I bristle at the whole "don't bring politics into tech/etc." thing. And this community we're establishing is **heavily steeped** in politics, it effects 99.9% of our work.

But I realize that mastodon is largely a group of _other folks' communities_ and they have established rules of how they want to engage with the world. And moreover, this is a space largely created by queer and underrepresented folks and allies originally. I personally am trying to be sensitive to the established fediverse norms and not act like a colonizer.

And also - _yes we can indeed expect folks in our community to hide stuff we find unpalatable_, that's what we do in communities. We're not saying "don't talk about it," we're saying be kind in how you talk about it. Just like any other content warning. 

(Moreover, I also *love* that CWs can easily help me filter out the noise of lots of topics _I don't care about_, e.g. sports.)

Politics, and US politics in particular, can be triggering for folks. What we do on `local` is one thing, but posting publicly impacts the world around us. And we should approach those spaces respectfully. That's why I think this belongs under Norms (and not COC necessarily). 

But this is just my personal, single opinion! Totally open to more conversation here, of course!

**Comment by annepetersen** [comment]
Helpful discussion, and thanks for this! 

And yep, agreed on this for sure: "be kind in how you talk about it." It's worth saying _that_ precisely — possibly broken out somewhere, in the Code of Care or elsewhere.

A lot of what you've said here is context that not everyone will have, and will be needed to help folks understand the _why_ of some of these guidelines. And if what we'd recommend is different on local than publicly, that should be outlined here too.

This said, the CW recommendation here right now is super wiggly: what, precisely, "off-topic" is here is _super arguable_ until it's been documented or otherwise established.

Also super open to more conversation here: I wonder if anyone else might want to chime in.

**Comment by BryceStevenWilley** [comment]
I also 100% agree with what's already been said about everything being politics, and that "off-topic" is very arguable. I'm a fan of [my current instance's etiquette on CWs](https://github.com/weirderearth/weirder-rules/blob/main/rules-and-etiquette.md#use-cws-for-sensitive-content), specifically list of things that you are encouraged to CW, and the mention that:

>  "this is important, so I won't CW" and "this is urgent, so I won't CW" are non-sequiturs - the importance and the urgency have nothing to do with whether that content is more accessible with a content warning

Specifically, my interpretation is that "more accessible" here means that others in the fediverse are less likely to mute or block accounts, and that CW'd content is more likely to get boosted more widely and have a wider reach than otherwise. That might be more useful context in explaining the norms.

I also think it's worth mentioning that people shouldn't feel like they have to CW their identities; this might help balance avoiding colonizing existing spaces, and not put extra onus on new comers from minority groups?:

> We don't want to ask anyone to CW their identities. We particularly don't want to ask marginalized people to CW their marginalization

Politics is a trickier one for what we want to encourage, given "everything is politics", and the general focus of the server (civic tech). I don't have any good ideas there. ☹️

**Comment by krusynth** [comment]
Hi again, I've had a few conversations with folks and I've come around on my thinking on this. 

I 1000% agree with Bryce's comment that `people shouldn't feel like they have to CW their identities`.  If everyone here is in agreement (it sounds like we are!) I'll remove the politics language from the CW bit?  (Please thumbs-up this comment if y'all are in agreement).
